apiVersion: apps/v1
kind: Deployment
metadata:
  name: cubejs-deployment
  labels:
    app: cubejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cubejs
  template:
    metadata:
      labels:
        app: cubejs
    spec:
      containers:
      - name: cubejs-container
        image: docker.io/your-docker-username/cubejs-app:latest  # This gets updated in the Jenkins pipeline
        ports:
        - containerPort: 4000  # Default port for Cube.js
        env:
        - name: CUBEJS_DB_HOST
          value: "<YOUR_DB_HOST>"
        - name: CUBEJS_DB_USER
          value: "<YOUR_DB_USER>"
        - name: CUBEJS_DB_PASS
          value: "<YOUR_DB_PASS>"
        - name: CUBEJS_DB_NAME
          value: "<YOUR_DB_NAME>"
