apiVersion: apps/v1
kind: Deployment
metadata:
  name: cubejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cubejs
  template:
    metadata:
      labels:
        app: cubejs
    spec:
      containers:
      - name: cubejs
        image: thulasiramteja/cubejs:latest  # Ensure this image is correct for your setup
        ports:
        - containerPort: 4000
        - containerPort: 15432
        env:
        - name: CUBEJS_DEV_MODE
          value: "true"
        volumeMounts:
        - name: cube-config  # This must match the volume name specified below
          mountPath: /cube/conf
      volumes:
      - name: cube-config
        hostPath:
          path: /path/to/your/cubejs/config  # Update this to match your host path
