apiVersion: apps/v1
kind: Deployment
metadata:
  name: cubejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cubejs
  template:
    metadata:
      labels:
        app: cubejs
    spec:
      containers:
      - name: cubejs
        image: thulasiramteja/cubejs:latest  # Updated to reflect the new DockerHub image
        ports:
        - containerPort: 4000
        - containerPort: 15432
        env:
        - name: CUBEJS_DEV_MODE
          value: "true"
        volumeMounts:
        - name: cube-config
          mountPath: /cube/conf
  volumes:
  - name: cube-config
    hostPath:
      path: /path/to/your/cubejs/config  # Replace with the actual path to your Cube.js config files
