apiVersion: v1
kind: Service
metadata:
  name: cubejs-service
spec:
  selector:
    app: cubejs
  ports:
    - protocol: TCP
      port: 80  # This is the external port that users will access
      targetPort: 4000  # Internal container port that Cube.js application uses
  type: NodePort  # Expose the service externally using a NodePort
